### Tiny data for tests only
tiny_parquet:
    data_root: ../../../data/
    data_format: parquet
    train_data: ../../../data/tiny_parquet/train.parquet
    valid_data: ../../../data/tiny_parquet/valid.parquet
    test_data: ../../../data/tiny_parquet/test.parquet

frappe_x1:
    data_format: csv
    data_root: ../../../data/
    feature_cols:
        - active: true
          dtype: float
          name: [ user, item, daytime, weekday, isweekend, homework, cost, weather, country,
                  city ]
          type: categorical
    label_col: { dtype: float, name: label }
    min_categr_count: 1
    test_data: ../../../data/frappe_x1/test.csv
    train_data: ../../../data/frappe_x1/train.csv
    valid_data: ../../../data/frappe_x1/valid.csv